# Generated by Django 4.1.4 on 2022-12-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.AddField(
            model_name='ticket',
            name='places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='api.places'),
            preserve_default=False,
        ),
    ]
