# Generated by Django 3.2 on 2022-12-23 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('place_type', models.CharField(choices=[('RS', 'Плацкарт'), ('CP', 'Купе'), ('SW', 'СВ')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='rails.carriage')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trains_end', to='rails.city')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trains_start', to='rails.city')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='rails.carriage')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='rails.places')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='rails.train')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carriage',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriages', to='rails.train'),
        ),
    ]
